name: Azure Web App CI/CD

on:
  push:
    branches:
      - main
      - enhancement-chat-widget  # Add the feature branch here
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - enhancement-chat-widget  # Ensure PRs for this branch are considered

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/webapps-deploy@v2
        with:
          app_name: <your-app-name> # Set your Azure Web App name
          publish_profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: .  # Assuming the whole repository is the app source

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/webapps-deploy@v2
        with:
          app_name: <your-app-name> # Set your Azure Web App name
          publish_profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          action: "close"
